# permissions for end users to view webapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webapp-viewer-role
rules:
- apiGroups:
  - mobfun.infinitefun.cn
  resources:
  - webapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mobfun.infinitefun.cn
  resources:
  - webapps/status
  verbs:
  - get
