apiVersion: mobfun.infinitefun.cn/v1
kind: WebApp
metadata:
  name: webapp-sample
spec:
  replicas: 2
  image: data.process.com:28080/public/transmission-resource-platform:20220407133556
  env:
    - name: LOCAL_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  hostPathMount:
#    - spath: /data
#      dpath: /data
    - spath: /data1
      dpath: /data1
  hostBinding:
    - node-10-170-66-25
  hostName: www.mobfunv1.com
  contextPath: /fff
  promTail:
    image:
    PromtailYml: |
      server:
        http_listen_port: 9080
        grpc_listen_port: 0
        grpc_server_max_recv_msg_size: 15728640
        grpc_server_max_send_msg_size: 15728640

      positions:
        filename: /planning-data/promtail/positions.yaml # This location needs to be writeable by promtail.

      client:
        url: http://loki01.prometheus.svc.cluster.local:3100/loki/api/v1/push


      scrape_configs:
        - job_name: planning
          pipeline_stages:
          static_configs:
            - targets:
                - localhost
              labels:
                job: planning
                host: 192.168.12.7
                __path__: /planning-data/pre-planning*